Repository PatrykKuniczak/memesChat, pull requests merged in 2023-04, with the labels that each got.

#107 Fix buggy layout on mobile view
  frontend/src/assets/styles/theme.ts
  frontend/src/components/chatInput/ChatInput.styled.ts
  frontend/src/components/messageSearchBar/MessageSearchBar.styled.ts
Labels: bug

#109 Feature/avatar on mobile #105
  frontend/src/components/menu/Menu.styled.ts
  frontend/src/components/menu/Menu.tsx
  frontend/src/components/modals/dropdown/DropdownMenu.tsx
  frontend/src/components/modals/dropdown/useDropdownMenu.ts
Labels: enhancement

#110 Fix getting and deleting userAvatar
  api/src/auth/services/auth.service.ts
  api/src/users/controllers/users-controller.ts
  api/src/users/decorators/user.decorator.ts
  api/src/users/services/users.service.ts
  api/src/users/users.module.ts
  api/src/usersAvatar/controllers/usersAvatar-controller.ts
  api/src/usersAvatar/services/usersAvatar.service.ts
Labels: bug

#112 Fix Avatar serving
  api/src/usersAvatar/controllers/usersAvatar-controller.ts
Labels: bug

#114 Feature/Create more description for swagger endpoints
  api/src/auth/controllers/auth-controller.ts
  api/src/messages/controllers/messages.controller.ts
  api/src/swagger/swagger.config.ts
  api/src/users/controllers/users-controller.ts
  api/src/usersAvatar/controllers/usersAvatar-controller.ts
  api/src/usersAvatar/services/usersAvatar.service.ts
Labels: enhancement

#118 Fix Communication between docker containers
  api/.dockerignore
  api/Dockerfile
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Form/useForm.ts
  frontend/src/index.tsx
  ws/.dockerignore
  ws/Dockerfile
Labels: bug, enhancement

#128 Add wrapper for hook to reduce code
  frontend/src/components/message/DeleteMessageModal/DeleteMessageModal.tsx
  frontend/src/components/message/Message.tsx
  frontend/src/components/message/useMessage.ts
  frontend/src/components/modals/accountDelete/DeleteAccountModal.tsx
  frontend/src/components/modals/dropdown/useDropdownMenu.ts
  frontend/src/components/modals/editAccount/EditAccountModal.tsx
  frontend/src/components/modals/removeAvatar/DeleteAvatarModal.tsx
  frontend/src/hooks/useClickOutside.ts
Labels: enhancement

#123 Feature/upadate ws packages
  ws/package-lock.json
Labels: enhancement

#126 Feature/Change env names
  CONTRIBUTION.md
  frontend/config/env/example.dev.env
  frontend/config/env/example.mobile.env
  frontend/src/components/Form/useForm.ts
  frontend/src/components/modals/editAccount/useModalEditUsername.ts
  frontend/src/hooks/useMessageValidation.ts
  frontend/src/index.tsx
  ws/config/env/example.dev.env
  ws/config/env/example.mobile.env
  ws/package.json
  ws/src/main.ts
  ws/src/messages/messages.gateway.ts
  ws/src/users/users.gateway.ts
Labels: enhancement

#130 Fix/Handle connection exception
  ws/src/exceptions/AxiosExceptionFilter.ts
Labels: bug

#125 Feature/Set off swagger
  CONTRIBUTION.md
  api/config/env/example.dev.env
  api/config/env/example.mobile.env
  api/package.json
  api/src/main.ts
Labels: enhancement

#134 Fix/userAvatar name length
  api/src/usersAvatar/model/usersAvatar.entity.ts
Labels: enhancement

#135 Fix/UI bugs
  frontend/src/components/menu/Menu.styled.ts
  frontend/src/components/message/Message.styled.ts
  frontend/src/components/modals/dropdown/DropdownMenu.styled.ts
  frontend/src/components/modals/dropdown/DropdownMenu.tsx
Labels: bug

#137 Feature/Create max size for avatar image
  api/src/users/controllers/users-controller.ts
  frontend/src/components/modals/editAccount/EditAccountModal.tsx
Labels: enhancement

#141 Feature/Refactor api for correctly behavior
  CONTRIBUTION.md
  api/src/auth/strategies/jwt.strategy.ts
  api/src/main.ts
  api/src/messages/controllers/messages.controller.ts
  api/src/messages/model/dto/create-message.dto.ts
  api/src/messages/model/dto/update-message.dto.ts
  api/src/messages/model/message.entity.ts
  api/src/messages/services/messages.service.ts
  api/src/swagger/swagger.config.ts
  api/src/users/controllers/users-controller.ts
  api/src/users/model/dto/update-user.dto.ts
  api/src/users/model/users.entity.ts
  api/src/users/services/users.service.ts
  api/src/usersAvatar/controllers/usersAvatar-controller.ts
  api/src/usersAvatar/model/usersAvatar.entity.ts
  api/src/usersAvatar/services/usersAvatar.service.ts
Labels: enhancement

#145 Fix/Hint hover
  frontend/src/assets/styles/theme.ts
Labels: bug

#146 Fix/Mobile layout
  .prettierrc
  frontend/src/components/chat/Chat.styled.ts
  frontend/src/components/chatInput/ChatInput.styled.ts
  frontend/src/components/menu/Menu.styled.ts
  frontend/src/components/message/useMessage.ts
  frontend/src/components/messageSearchBar/MessageSearchBar.styled.ts
  frontend/src/components/messages/Messages.styled.ts
  frontend/src/components/modals/dropdown/DropdownMenu.styled.ts
  frontend/src/components/modals/editAccount/EditAccountModal.tsx
  frontend/src/components/users/Users.styled.ts
  frontend/src/pages/home/Home.styled.ts
Labels: bug
